Sender: LSF System <lsfadmin@lo-s4-011>
Subject: Job 1043086: <python train.py> in cluster <leonhard> Exited

Job <python train.py> was submitted from host <lo-login-02> by user <erikbe> in cluster <leonhard> at Fri Dec 21 13:22:40 2018
Job was executed on host(s) <lo-s4-011>, in queue <gpu.120h>, as user <erikbe> in cluster <leonhard> at Fri Dec 21 13:22:44 2018
</cluster/home/erikbe> was used as the home directory.
</cluster/scratch/erikbe/DL-Project> was used as the working directory.
Started at Fri Dec 21 13:22:44 2018
Terminated at Sat Dec 22 16:11:30 2018
Results reported at Sat Dec 22 16:11:30 2018

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python train.py
------------------------------------------------------------

Exited with exit code 1.

Resource usage summary:

    CPU time :                                   134431.41 sec.
    Max Memory :                                 29630 MB
    Average Memory :                             16876.64 MB
    Total Requested Memory :                     50000.00 MB
    Delta Memory :                               20370.00 MB
    Max Swap :                                   88 MB
    Max Processes :                              3
    Max Threads :                                57
    Run time :                                   96554 sec.
    Turnaround time :                            96530 sec.

The output (if any) follows:

Using TensorFlow backend.
2018-12-21 13:22:51.252716: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/cluster/home/erikbe/.local/lib64/python2.7/site-packages/keras/callbacks.py:1065: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '
WARNING:tensorflow:From /cluster/home/erikbe/.local/lib64/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Epoch 1/100
 - 96501s - loss: 0.7219 - dice_coeff: 0.5974 - val_loss: 0.6316 - val_dice_coeff: 0.6614
Traceback (most recent call last):
  File "train.py", line 162, in <module>
    validation_steps=np.ceil(float(len(ids_valid_split)) / float(batch_size)))
  File "/cluster/home/erikbe/.local/lib64/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/cluster/home/erikbe/.local/lib64/python2.7/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/cluster/home/erikbe/.local/lib64/python2.7/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/cluster/home/erikbe/.local/lib64/python2.7/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/cluster/home/erikbe/.local/lib64/python2.7/site-packages/keras/callbacks.py", line 444, in on_epoch_end
    self.model.save_weights(filepath, overwrite=True)
  File "/cluster/home/erikbe/.local/lib64/python2.7/site-packages/keras/engine/network.py", line 1114, in save_weights
    raise ImportError('`save_weights` requires h5py.')
ImportError: `save_weights` requires h5py.
